// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

// Protobuf Java Version: 3.25.0
package org.anas.paymentfraud.engineevalution.proto;

public final class Transaction {
  private Transaction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionFrequencyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transaction.TransactionFrequency)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique identifier of the customer
     * </pre>
     *
     * <code>string customer_id = 1;</code>
     * @return The customerId.
     */
    String getCustomerId();
    /**
     * <pre>
     * Unique identifier of the customer
     * </pre>
     *
     * <code>string customer_id = 1;</code>
     * @return The bytes for customerId.
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();

    /**
     * <pre>
     * Transactions in the past 1 minute
     * </pre>
     *
     * <code>uint32 trx_1m = 2;</code>
     * @return The trx1m.
     */
    int getTrx1M();

    /**
     * <pre>
     * Transactions in the past 10 minutes
     * </pre>
     *
     * <code>uint32 trx_10m = 3;</code>
     * @return The trx10m.
     */
    int getTrx10M();

    /**
     * <pre>
     * Transactions in the past 1 hour
     * </pre>
     *
     * <code>uint32 trx_1h = 4;</code>
     * @return The trx1h.
     */
    int getTrx1H();

    /**
     * <pre>
     * Transactions in the past 3 hours
     * </pre>
     *
     * <code>uint32 trx_3h = 5;</code>
     * @return The trx3h.
     */
    int getTrx3H();

    /**
     * <pre>
     * Transactions in the past 24 hours
     * </pre>
     *
     * <code>uint32 trx_24h = 6;</code>
     * @return The trx24h.
     */
    int getTrx24H();
  }
  /**
   * <pre>
   * Transaction frequency data used for prediction
   * </pre>
   *
   * Protobuf type {@code transaction.TransactionFrequency}
   */
  public static final class TransactionFrequency extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:transaction.TransactionFrequency)
      TransactionFrequencyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionFrequency.newBuilder() to construct.
    private TransactionFrequency(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionFrequency() {
      customerId_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransactionFrequency();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Transaction.internal_static_transaction_TransactionFrequency_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Transaction.internal_static_transaction_TransactionFrequency_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Transaction.TransactionFrequency.class, Transaction.TransactionFrequency.Builder.class);
    }

    public static final int CUSTOMER_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object customerId_ = "";
    /**
     * <pre>
     * Unique identifier of the customer
     * </pre>
     *
     * <code>string customer_id = 1;</code>
     * @return The customerId.
     */
    @Override
    public String getCustomerId() {
      Object ref = customerId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        customerId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Unique identifier of the customer
     * </pre>
     *
     * <code>string customer_id = 1;</code>
     * @return The bytes for customerId.
     */
    @Override
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      Object ref = customerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRX_1M_FIELD_NUMBER = 2;
    private int trx1M_ = 0;
    /**
     * <pre>
     * Transactions in the past 1 minute
     * </pre>
     *
     * <code>uint32 trx_1m = 2;</code>
     * @return The trx1m.
     */
    @Override
    public int getTrx1M() {
      return trx1M_;
    }

    public static final int TRX_10M_FIELD_NUMBER = 3;
    private int trx10M_ = 0;
    /**
     * <pre>
     * Transactions in the past 10 minutes
     * </pre>
     *
     * <code>uint32 trx_10m = 3;</code>
     * @return The trx10m.
     */
    @Override
    public int getTrx10M() {
      return trx10M_;
    }

    public static final int TRX_1H_FIELD_NUMBER = 4;
    private int trx1H_ = 0;
    /**
     * <pre>
     * Transactions in the past 1 hour
     * </pre>
     *
     * <code>uint32 trx_1h = 4;</code>
     * @return The trx1h.
     */
    @Override
    public int getTrx1H() {
      return trx1H_;
    }

    public static final int TRX_3H_FIELD_NUMBER = 5;
    private int trx3H_ = 0;
    /**
     * <pre>
     * Transactions in the past 3 hours
     * </pre>
     *
     * <code>uint32 trx_3h = 5;</code>
     * @return The trx3h.
     */
    @Override
    public int getTrx3H() {
      return trx3H_;
    }

    public static final int TRX_24H_FIELD_NUMBER = 6;
    private int trx24H_ = 0;
    /**
     * <pre>
     * Transactions in the past 24 hours
     * </pre>
     *
     * <code>uint32 trx_24h = 6;</code>
     * @return The trx24h.
     */
    @Override
    public int getTrx24H() {
      return trx24H_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, customerId_);
      }
      if (trx1M_ != 0) {
        output.writeUInt32(2, trx1M_);
      }
      if (trx10M_ != 0) {
        output.writeUInt32(3, trx10M_);
      }
      if (trx1H_ != 0) {
        output.writeUInt32(4, trx1H_);
      }
      if (trx3H_ != 0) {
        output.writeUInt32(5, trx3H_);
      }
      if (trx24H_ != 0) {
        output.writeUInt32(6, trx24H_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, customerId_);
      }
      if (trx1M_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, trx1M_);
      }
      if (trx10M_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, trx10M_);
      }
      if (trx1H_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, trx1H_);
      }
      if (trx3H_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, trx3H_);
      }
      if (trx24H_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, trx24H_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Transaction.TransactionFrequency)) {
        return super.equals(obj);
      }
      Transaction.TransactionFrequency other = (Transaction.TransactionFrequency) obj;

      if (!getCustomerId()
          .equals(other.getCustomerId())) return false;
      if (getTrx1M()
          != other.getTrx1M()) return false;
      if (getTrx10M()
          != other.getTrx10M()) return false;
      if (getTrx1H()
          != other.getTrx1H()) return false;
      if (getTrx3H()
          != other.getTrx3H()) return false;
      if (getTrx24H()
          != other.getTrx24H()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CUSTOMER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerId().hashCode();
      hash = (37 * hash) + TRX_1M_FIELD_NUMBER;
      hash = (53 * hash) + getTrx1M();
      hash = (37 * hash) + TRX_10M_FIELD_NUMBER;
      hash = (53 * hash) + getTrx10M();
      hash = (37 * hash) + TRX_1H_FIELD_NUMBER;
      hash = (53 * hash) + getTrx1H();
      hash = (37 * hash) + TRX_3H_FIELD_NUMBER;
      hash = (53 * hash) + getTrx3H();
      hash = (37 * hash) + TRX_24H_FIELD_NUMBER;
      hash = (53 * hash) + getTrx24H();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Transaction.TransactionFrequency parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transaction.TransactionFrequency parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transaction.TransactionFrequency parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transaction.TransactionFrequency parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transaction.TransactionFrequency parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transaction.TransactionFrequency parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transaction.TransactionFrequency parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transaction.TransactionFrequency parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Transaction.TransactionFrequency parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Transaction.TransactionFrequency parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transaction.TransactionFrequency parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transaction.TransactionFrequency parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Transaction.TransactionFrequency prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Transaction frequency data used for prediction
     * </pre>
     *
     * Protobuf type {@code transaction.TransactionFrequency}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transaction.TransactionFrequency)
        Transaction.TransactionFrequencyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Transaction.internal_static_transaction_TransactionFrequency_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Transaction.internal_static_transaction_TransactionFrequency_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Transaction.TransactionFrequency.class, Transaction.TransactionFrequency.Builder.class);
      }

      // Construct using transaction.Transaction.TransactionFrequency.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        customerId_ = "";
        trx1M_ = 0;
        trx10M_ = 0;
        trx1H_ = 0;
        trx3H_ = 0;
        trx24H_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Transaction.internal_static_transaction_TransactionFrequency_descriptor;
      }

      @Override
      public Transaction.TransactionFrequency getDefaultInstanceForType() {
        return Transaction.TransactionFrequency.getDefaultInstance();
      }

      @Override
      public Transaction.TransactionFrequency build() {
        Transaction.TransactionFrequency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Transaction.TransactionFrequency buildPartial() {
        Transaction.TransactionFrequency result = new Transaction.TransactionFrequency(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Transaction.TransactionFrequency result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.customerId_ = customerId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.trx1M_ = trx1M_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.trx10M_ = trx10M_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.trx1H_ = trx1H_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.trx3H_ = trx3H_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.trx24H_ = trx24H_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Transaction.TransactionFrequency) {
          return mergeFrom((Transaction.TransactionFrequency)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Transaction.TransactionFrequency other) {
        if (other == Transaction.TransactionFrequency.getDefaultInstance()) return this;
        if (!other.getCustomerId().isEmpty()) {
          customerId_ = other.customerId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getTrx1M() != 0) {
          setTrx1M(other.getTrx1M());
        }
        if (other.getTrx10M() != 0) {
          setTrx10M(other.getTrx10M());
        }
        if (other.getTrx1H() != 0) {
          setTrx1H(other.getTrx1H());
        }
        if (other.getTrx3H() != 0) {
          setTrx3H(other.getTrx3H());
        }
        if (other.getTrx24H() != 0) {
          setTrx24H(other.getTrx24H());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                customerId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                trx1M_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                trx10M_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                trx1H_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                trx3H_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                trx24H_ = input.readUInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object customerId_ = "";
      /**
       * <pre>
       * Unique identifier of the customer
       * </pre>
       *
       * <code>string customer_id = 1;</code>
       * @return The customerId.
       */
      public String getCustomerId() {
        Object ref = customerId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          customerId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Unique identifier of the customer
       * </pre>
       *
       * <code>string customer_id = 1;</code>
       * @return The bytes for customerId.
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Unique identifier of the customer
       * </pre>
       *
       * <code>string customer_id = 1;</code>
       * @param value The customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        customerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier of the customer
       * </pre>
       *
       * <code>string customer_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerId() {
        customerId_ = getDefaultInstance().getCustomerId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier of the customer
       * </pre>
       *
       * <code>string customer_id = 1;</code>
       * @param value The bytes for customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        customerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int trx1M_ ;
      /**
       * <pre>
       * Transactions in the past 1 minute
       * </pre>
       *
       * <code>uint32 trx_1m = 2;</code>
       * @return The trx1m.
       */
      @Override
      public int getTrx1M() {
        return trx1M_;
      }
      /**
       * <pre>
       * Transactions in the past 1 minute
       * </pre>
       *
       * <code>uint32 trx_1m = 2;</code>
       * @param value The trx1m to set.
       * @return This builder for chaining.
       */
      public Builder setTrx1M(int value) {

        trx1M_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Transactions in the past 1 minute
       * </pre>
       *
       * <code>uint32 trx_1m = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrx1M() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trx1M_ = 0;
        onChanged();
        return this;
      }

      private int trx10M_ ;
      /**
       * <pre>
       * Transactions in the past 10 minutes
       * </pre>
       *
       * <code>uint32 trx_10m = 3;</code>
       * @return The trx10m.
       */
      @Override
      public int getTrx10M() {
        return trx10M_;
      }
      /**
       * <pre>
       * Transactions in the past 10 minutes
       * </pre>
       *
       * <code>uint32 trx_10m = 3;</code>
       * @param value The trx10m to set.
       * @return This builder for chaining.
       */
      public Builder setTrx10M(int value) {

        trx10M_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Transactions in the past 10 minutes
       * </pre>
       *
       * <code>uint32 trx_10m = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrx10M() {
        bitField0_ = (bitField0_ & ~0x00000004);
        trx10M_ = 0;
        onChanged();
        return this;
      }

      private int trx1H_ ;
      /**
       * <pre>
       * Transactions in the past 1 hour
       * </pre>
       *
       * <code>uint32 trx_1h = 4;</code>
       * @return The trx1h.
       */
      @Override
      public int getTrx1H() {
        return trx1H_;
      }
      /**
       * <pre>
       * Transactions in the past 1 hour
       * </pre>
       *
       * <code>uint32 trx_1h = 4;</code>
       * @param value The trx1h to set.
       * @return This builder for chaining.
       */
      public Builder setTrx1H(int value) {

        trx1H_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Transactions in the past 1 hour
       * </pre>
       *
       * <code>uint32 trx_1h = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrx1H() {
        bitField0_ = (bitField0_ & ~0x00000008);
        trx1H_ = 0;
        onChanged();
        return this;
      }

      private int trx3H_ ;
      /**
       * <pre>
       * Transactions in the past 3 hours
       * </pre>
       *
       * <code>uint32 trx_3h = 5;</code>
       * @return The trx3h.
       */
      @Override
      public int getTrx3H() {
        return trx3H_;
      }
      /**
       * <pre>
       * Transactions in the past 3 hours
       * </pre>
       *
       * <code>uint32 trx_3h = 5;</code>
       * @param value The trx3h to set.
       * @return This builder for chaining.
       */
      public Builder setTrx3H(int value) {

        trx3H_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Transactions in the past 3 hours
       * </pre>
       *
       * <code>uint32 trx_3h = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrx3H() {
        bitField0_ = (bitField0_ & ~0x00000010);
        trx3H_ = 0;
        onChanged();
        return this;
      }

      private int trx24H_ ;
      /**
       * <pre>
       * Transactions in the past 24 hours
       * </pre>
       *
       * <code>uint32 trx_24h = 6;</code>
       * @return The trx24h.
       */
      @Override
      public int getTrx24H() {
        return trx24H_;
      }
      /**
       * <pre>
       * Transactions in the past 24 hours
       * </pre>
       *
       * <code>uint32 trx_24h = 6;</code>
       * @param value The trx24h to set.
       * @return This builder for chaining.
       */
      public Builder setTrx24H(int value) {

        trx24H_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Transactions in the past 24 hours
       * </pre>
       *
       * <code>uint32 trx_24h = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrx24H() {
        bitField0_ = (bitField0_ & ~0x00000020);
        trx24H_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:transaction.TransactionFrequency)
    }

    // @@protoc_insertion_point(class_scope:transaction.TransactionFrequency)
    private static final Transaction.TransactionFrequency DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Transaction.TransactionFrequency();
    }

    public static Transaction.TransactionFrequency getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionFrequency>
        PARSER = new com.google.protobuf.AbstractParser<TransactionFrequency>() {
      @Override
      public TransactionFrequency parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TransactionFrequency> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TransactionFrequency> getParserForType() {
      return PARSER;
    }

    @Override
    public Transaction.TransactionFrequency getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PredictionResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transaction.PredictionResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Echoed Customer ID
     * </pre>
     *
     * <code>string customer_id = 1;</code>
     * @return The customerId.
     */
    String getCustomerId();
    /**
     * <pre>
     * Echoed Customer ID
     * </pre>
     *
     * <code>string customer_id = 1;</code>
     * @return The bytes for customerId.
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();

    /**
     * <pre>
     * True if prediction indicates non-fraudulent behavior
     * </pre>
     *
     * <code>bool is_transaction_legit = 2;</code>
     * @return The isTransactionLegit.
     */
    boolean getIsTransactionLegit();
  }
  /**
   * <pre>
   * Result of transaction-based prediction
   * </pre>
   *
   * Protobuf type {@code transaction.PredictionResult}
   */
  public static final class PredictionResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:transaction.PredictionResult)
      PredictionResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PredictionResult.newBuilder() to construct.
    private PredictionResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PredictionResult() {
      customerId_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PredictionResult();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Transaction.internal_static_transaction_PredictionResult_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Transaction.internal_static_transaction_PredictionResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Transaction.PredictionResult.class, Transaction.PredictionResult.Builder.class);
    }

    public static final int CUSTOMER_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object customerId_ = "";
    /**
     * <pre>
     * Echoed Customer ID
     * </pre>
     *
     * <code>string customer_id = 1;</code>
     * @return The customerId.
     */
    @Override
    public String getCustomerId() {
      Object ref = customerId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        customerId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Echoed Customer ID
     * </pre>
     *
     * <code>string customer_id = 1;</code>
     * @return The bytes for customerId.
     */
    @Override
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      Object ref = customerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_TRANSACTION_LEGIT_FIELD_NUMBER = 2;
    private boolean isTransactionLegit_ = false;
    /**
     * <pre>
     * True if prediction indicates non-fraudulent behavior
     * </pre>
     *
     * <code>bool is_transaction_legit = 2;</code>
     * @return The isTransactionLegit.
     */
    @Override
    public boolean getIsTransactionLegit() {
      return isTransactionLegit_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, customerId_);
      }
      if (isTransactionLegit_ != false) {
        output.writeBool(2, isTransactionLegit_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(customerId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, customerId_);
      }
      if (isTransactionLegit_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isTransactionLegit_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Transaction.PredictionResult)) {
        return super.equals(obj);
      }
      Transaction.PredictionResult other = (Transaction.PredictionResult) obj;

      if (!getCustomerId()
          .equals(other.getCustomerId())) return false;
      if (getIsTransactionLegit()
          != other.getIsTransactionLegit()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CUSTOMER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerId().hashCode();
      hash = (37 * hash) + IS_TRANSACTION_LEGIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsTransactionLegit());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Transaction.PredictionResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transaction.PredictionResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transaction.PredictionResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transaction.PredictionResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transaction.PredictionResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transaction.PredictionResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transaction.PredictionResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transaction.PredictionResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Transaction.PredictionResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Transaction.PredictionResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transaction.PredictionResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transaction.PredictionResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Transaction.PredictionResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Result of transaction-based prediction
     * </pre>
     *
     * Protobuf type {@code transaction.PredictionResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transaction.PredictionResult)
        Transaction.PredictionResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Transaction.internal_static_transaction_PredictionResult_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Transaction.internal_static_transaction_PredictionResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Transaction.PredictionResult.class, Transaction.PredictionResult.Builder.class);
      }

      // Construct using transaction.Transaction.PredictionResult.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        customerId_ = "";
        isTransactionLegit_ = false;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Transaction.internal_static_transaction_PredictionResult_descriptor;
      }

      @Override
      public Transaction.PredictionResult getDefaultInstanceForType() {
        return Transaction.PredictionResult.getDefaultInstance();
      }

      @Override
      public Transaction.PredictionResult build() {
        Transaction.PredictionResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Transaction.PredictionResult buildPartial() {
        Transaction.PredictionResult result = new Transaction.PredictionResult(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Transaction.PredictionResult result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.customerId_ = customerId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.isTransactionLegit_ = isTransactionLegit_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Transaction.PredictionResult) {
          return mergeFrom((Transaction.PredictionResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Transaction.PredictionResult other) {
        if (other == Transaction.PredictionResult.getDefaultInstance()) return this;
        if (!other.getCustomerId().isEmpty()) {
          customerId_ = other.customerId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getIsTransactionLegit() != false) {
          setIsTransactionLegit(other.getIsTransactionLegit());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                customerId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                isTransactionLegit_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object customerId_ = "";
      /**
       * <pre>
       * Echoed Customer ID
       * </pre>
       *
       * <code>string customer_id = 1;</code>
       * @return The customerId.
       */
      public String getCustomerId() {
        Object ref = customerId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          customerId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Echoed Customer ID
       * </pre>
       *
       * <code>string customer_id = 1;</code>
       * @return The bytes for customerId.
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Echoed Customer ID
       * </pre>
       *
       * <code>string customer_id = 1;</code>
       * @param value The customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        customerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Echoed Customer ID
       * </pre>
       *
       * <code>string customer_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerId() {
        customerId_ = getDefaultInstance().getCustomerId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Echoed Customer ID
       * </pre>
       *
       * <code>string customer_id = 1;</code>
       * @param value The bytes for customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        customerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean isTransactionLegit_ ;
      /**
       * <pre>
       * True if prediction indicates non-fraudulent behavior
       * </pre>
       *
       * <code>bool is_transaction_legit = 2;</code>
       * @return The isTransactionLegit.
       */
      @Override
      public boolean getIsTransactionLegit() {
        return isTransactionLegit_;
      }
      /**
       * <pre>
       * True if prediction indicates non-fraudulent behavior
       * </pre>
       *
       * <code>bool is_transaction_legit = 2;</code>
       * @param value The isTransactionLegit to set.
       * @return This builder for chaining.
       */
      public Builder setIsTransactionLegit(boolean value) {

        isTransactionLegit_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * True if prediction indicates non-fraudulent behavior
       * </pre>
       *
       * <code>bool is_transaction_legit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsTransactionLegit() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isTransactionLegit_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:transaction.PredictionResult)
    }

    // @@protoc_insertion_point(class_scope:transaction.PredictionResult)
    private static final Transaction.PredictionResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Transaction.PredictionResult();
    }

    public static Transaction.PredictionResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PredictionResult>
        PARSER = new com.google.protobuf.AbstractParser<PredictionResult>() {
      @Override
      public PredictionResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PredictionResult> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PredictionResult> getParserForType() {
      return PARSER;
    }

    @Override
    public Transaction.PredictionResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transaction_TransactionFrequency_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transaction_TransactionFrequency_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transaction_PredictionResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transaction_PredictionResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021transaction.proto\022\013transaction\"}\n\024Tran" +
      "sactionFrequency\022\023\n\013customer_id\030\001 \001(\t\022\016\n" +
      "\006trx_1m\030\002 \001(\r\022\017\n\007trx_10m\030\003 \001(\r\022\016\n\006trx_1h" +
      "\030\004 \001(\r\022\016\n\006trx_3h\030\005 \001(\r\022\017\n\007trx_24h\030\006 \001(\r\"" +
      "E\n\020PredictionResult\022\023\n\013customer_id\030\001 \001(\t" +
      "\022\034\n\024is_transaction_legit\030\002 \001(\0102a\n\022Transa" +
      "ctionService\022K\n\007Predict\022!.transaction.Tr" +
      "ansactionFrequency\032\035.transaction.Predict" +
      "ionResultb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_transaction_TransactionFrequency_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transaction_TransactionFrequency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transaction_TransactionFrequency_descriptor,
        new String[] { "CustomerId", "Trx1M", "Trx10M", "Trx1H", "Trx3H", "Trx24H", });
    internal_static_transaction_PredictionResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_transaction_PredictionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transaction_PredictionResult_descriptor,
        new String[] { "CustomerId", "IsTransactionLegit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
