lowercaseOutputName: true
rules:
  # Kafka Producer Metrics (kafka.producer:type=producer-metrics,client-id=reader-producer)
  - pattern: 'kafka.producer<type=producer-metrics, client-id=(.+), name=(.+)><>Value'
    name: kafka_producer_$2
    labels:
      client_id: "$1"
    help: "Kafka producer metric $2 for client $1"
    type: GAUGE

  # Kafka Producer App Info (kafka.producer:type=app-info,client-id=reader-producer)
  - pattern: 'kafka.producer<type=app-info, client-id=(.+)><>start-time-ms'
    name: kafka_producer_start_time_seconds
    labels:
      clientId: "$1"
    help: "Kafka producer start time in seconds"
    type: GAUGE
    valueFactor: 0.001
  - pattern: 'kafka.producer<type=app-info, client-id=(.+)><>(commit-id|version): (.+)'
    name: kafka_producer_$2_info
    value: 1
    labels:
      clientId: "$1"
      $2: "$3"
    help: "Kafka producer version and commit-id"
    type: GAUGE

  # Generic rule for other Kafka producer metrics
  - pattern: 'kafka.producer<type=producer-metrics, client-id=(.+)><>(.+-total|.+-avg|.+-rate|.+-count)'
    name: kafka_producer_$2
    labels:
      client_id: "$1"
    help: "Kafka producer metric $2"
    type: GAUGE